ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SportsStore.WebUI.Models
{
	public class CartIndexViewModel
	{
		public Cart Cart { get; set; }
		public string ReturnUrl { get; set; }
	}
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SportsStore.WebUI.Models
{
	public class PagingInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }
		public int TotalPages {
			get { return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage); }
		}
	}
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Models/ProductsListViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SportsStore.WebUI.Models
{
	public class ProductsListViewModel
	{
		public IEnumerable<Product> Products { get; set; }
		public PagingInfo PagingInfo { get; set; }
		public string CurrentCategory { get; set; }
	}
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
	public class CartController : Controller
	{

		#region Fields

		private readonly IProductRepository modProductRepository;
		private readonly IOrderProcessor modOrderProcessor;

		#endregion

		#region Properties

		#endregion

		#region Ctor

		public CartController(IProductRepository repo, IOrderProcessor orderProcessor)
		{
			modProductRepository = repo;
			modOrderProcessor = orderProcessor;
		}

		#endregion

		#region Public Methods

		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			if(cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("", "Sorry, your cart is empty");
			}
			if (ModelState.IsValid)
			{
				modOrderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}

		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}

		public PartialViewResult Summary(Cart cart)
		{
			return PartialView(cart);
		}

		public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
		{
			Product product = modProductRepository.Products
							.FirstOrDefault(x => x.ProductID == productId);

			if(product!=null)
			{
				cart.AddItem(product, 1);
			}

			return RedirectToAction("Index", new { returnUrl = returnUrl});
		}

		public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
		{
			Product product = modProductRepository.Products
							.FirstOrDefault(x => x.ProductID == productId);
			if (product != null)
			{
				cart.RemoveLine(product);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel
				{ Cart = cart, ReturnUrl = returnUrl});
		}

		#endregion

		#region Private Methods

		private Cart GetCart()
		{
			Cart cart = Session["Cart"] as Cart;
			if(cart == null)
			{
				cart = new Cart();
				Session["Cart"] = cart;
			}

			return cart;
		}

		#endregion

		#region Protected Methods

		#endregion
	}
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
	public class NavController : Controller
	{
		private readonly IProductRepository modRepository;

		public NavController(IProductRepository repo)
		{
			modRepository = repo;
		}

		public PartialViewResult Menu(string category = null)
		{
			ViewBag.SelectedCategory = category;
			IEnumerable<string> categories = modRepository.Products
													.Select(x => x.Category)
													.Distinct()
													.OrderBy(x => x);

			return PartialView(categories);
		}

	}
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
	public class ProductController : Controller
	{

		#region Fields

		private IProductRepository modProductRepository;

		#endregion

		#region Properties

		public int PageSize { get; set; }

		#endregion

		#region Ctor

		public ProductController(IProductRepository productRepo)
		{
			modProductRepository = productRepo;
			PageSize = 4;
		}

		#endregion

		#region Public Methods

		public ActionResult Index()
		{
			return View();
		}

		public ViewResult List(string category, int page = 1)
		{
			var products = modProductRepository.Products.ToList();
			products = String.IsNullOrWhiteSpace(category)
				? products
        : products.Where(x => x.Category == null || x.Category == category).ToList();

			ProductsListViewModel vm = new ProductsListViewModel
			{
				Products = products.OrderBy(x => x.ProductID)
														.Skip((page - 1) * PageSize)
														.Take(PageSize),
				PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = PageSize, TotalItems = products.Count() },
				CurrentCategory = category
			};

			return View(vm);
		}

		#endregion

		#region Private Methods

		#endregion

		#region Protected Methods

		#endregion

	}
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails
@{
  ViewBag.Title = "SportsStore: Checkout";
}
<h2>Checkout now</h2>
<p>Please enter your details, and we will ship your goods right away!</p>
@using (Html.BeginForm())
{
  @Html.ValidationSummary()
<h3>Ship to</h3>
<div class="form-group">
    <label>Name</label>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
</div>

<h3>Address</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if(property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
      <div class="form-group">
          <label>
              @(property.DisplayName??property.PropertyName)
          </label>
          @Html.TextBox(property.PropertyName, null, new { @class="form-control"})
      </div>
        }
    }
@*<div class="form-group">
    <label>Line 1:</label>
    @Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
</div>
<div class="form-group">
    <label>Line 2:</label>
    @Html.TextBoxFor(x => x.Line2, new { @class = "form-control" })
</div>
<div class="form-group">
    <label>Line 3:</label>
    @Html.TextBoxFor(x => x.Line3, new { @class = "form-control" })
</div>
<div class="form-group">
    <label>City:</label>
    @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
</div>
<div class="form-group">
    <label>State:</label>
    @Html.TextBoxFor(x => x.State, new { @class = "form-control" })
</div>
<div class="form-group">
    <label>Zip:</label>
    @Html.TextBoxFor(x => x.Zip, new { @class = "form-control" })
</div>
<div class="form-group">
    <label>Country:</label>
    @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
</div>*@
<h3>Options</h3>
<div class="checkbox">
    <label>
        @Html.EditorFor(x => x.GiftWrap)
        Gift frap these items
    </label>
</div>
<div class="text-center">
    <input class="btn btn-primary" type="submit" value="Compare order" />
</div>
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Cart/Completed.cshtml
@{ 
  ViewBag.Title = "SportsStore: Order Submitted";
}
<h2>Thanks!</h2>
Thanks for placing your order. We will ship your goods as soon as possible.

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel
@{ 
  ViewBag.Title = "Sports store: Your Cart";
}

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>Your Cart</h2>
<table class="table" id="cartTable">
    <thead>
        <tr>Quantity</tr>
        <tr>Item</tr>
        <tr class="text-right">Price</tr>
        <tr class="text-right">Subtotal</tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cart.Lines)
        {
          <tr>
              <td class="text-center">@item.Quantity</td>
              <td class="text-left">@item.Product.Name</td>
              <td class="text-right">@item.Product.Price.ToString("c")</td>
              <td class="text-right">@((item.Product.Price*@item.Quantity).ToString("c"))</td>
              <td>
                  @using(Html.BeginForm("RemoveFromCart", "Cart"))
                  {
                    @Html.Hidden("ProductId", item.Product.ProductID)
                    @Html.HiddenFor(x=>x.ReturnUrl)
                    <input class="btn btn-sm btn-warning" type="submit" value="Remove"/>
                  }
              </td>
          </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", "Checkout", null, new { @class="btn btn-primary"})
</div>

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart
<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart",
  new { returnUrl = Request.Url.PathAndQuery},
  new { @class = "btn btn-default navbar-btn"}
  )
</div>

<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Lines.Sum(x=>x.Quantity) items
    @Model.ComputeTotalValue().ToString("c")
</div>

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null,
    new { @class = "btn btn-block btn-default btn-lg"})

@foreach (var link in Model)
{
  @Html.RouteLink(link,
        new
        {
            controller = "Product",
            action = "List",
            category = link,
            page = 1
        },
                new
                {
                    @class = "btn btn-block btn-default btn-lg"
                        + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
                }
  )
}

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Product/List.cshtml
@using SportsStore.Domain.Entities
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var item in Model.Products)
{
  @Html.Partial("ProductSummary", item);
}

<div class="btn btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x=>Url.Action("List", 
        new { page = x, category = Model.CurrentCategory }))
</div>

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
      <div class="pull-right">
          @Html.HiddenFor(x=>x.ProductID)
          @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
          <input type="submit" class="btn btn-success" value="Add to cart"/>
      </div>
    }
    <span class="lead">@Model.Description</span>

</div>

ASP.Net/SampleProAspNetMVC5/SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet"/>
    <title>@ViewBag.Title - My ASP.NET Application</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>